/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbmproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MONIRU CMY
 */
public class SelectSubjectFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form SelectSubjectFrame2
     */
    String url = "jdbc:mysql://localhost:3306/nsbm";
    String username = "root";
    String password = "";
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet res = null;

    Dbos db = new Dbos(); //creating the database object related to student registration in the system
    DbMarks dbm = new DbMarks(); // creating the database object related to student marks

    String stu_id, faculty;
    String course_tps;

    public SelectSubjectFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        select_subject_1 = new javax.swing.JTextField();
        select_subject_2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        select_subject_3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        select_subject_4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combo_subject1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        combo_subject2 = new javax.swing.JComboBox<>();
        txt_year1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_semester1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        select_subject_5 = new javax.swing.JTextField();
        select_subject_6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        select_subject_7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        select_subject_8 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        combo_subject3 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        combo_subject4 = new javax.swing.JComboBox<>();
        txt_year2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_semester2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Subjects");

        jLabel2.setText("Compulosory Subjects");

        jLabel3.setText("Subject 1");

        jLabel4.setText("Subject 2");

        select_subject_1.setEditable(false);
        select_subject_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_subject_1ActionPerformed(evt);
            }
        });

        select_subject_2.setEditable(false);
        select_subject_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_subject_2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Subject 3");

        select_subject_3.setEditable(false);
        select_subject_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_subject_3ActionPerformed(evt);
            }
        });

        jLabel13.setText("Subject 4");

        select_subject_4.setEditable(false);
        select_subject_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_subject_4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(select_subject_4, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(select_subject_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(select_subject_2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(select_subject_1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_subject_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_subject_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_subject_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_subject_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jLabel5.setText("Optional Subjects");

        jLabel6.setText("Subject 1");

        combo_subject1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_subject1MouseClicked(evt);
            }
        });
        combo_subject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_subject1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Subject 2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 201, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_subject1, 0, 255, Short.MAX_VALUE)
                            .addComponent(combo_subject2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_subject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_subject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txt_year1.setEditable(false);

        jLabel9.setText("Year");

        txt_semester1.setEditable(false);

        jLabel10.setText("Semester");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_year1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_semester1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_semester1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel8.setText("Compulosory Subjects");

        jLabel11.setText("Subject 1");

        jLabel14.setText("Subject 2");

        select_subject_5.setEditable(false);
        select_subject_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_subject_5ActionPerformed(evt);
            }
        });

        select_subject_6.setEditable(false);
        select_subject_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_subject_6ActionPerformed(evt);
            }
        });

        jLabel15.setText("Subject 3");

        select_subject_7.setEditable(false);
        select_subject_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_subject_7ActionPerformed(evt);
            }
        });

        jLabel16.setText("Subject 4");

        select_subject_8.setEditable(false);
        select_subject_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_subject_8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(select_subject_8, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(select_subject_7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(select_subject_6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(select_subject_5, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_subject_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_subject_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_subject_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_subject_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jLabel17.setText("Optional Subjects");

        jLabel18.setText("Subject 1");

        combo_subject3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_subject3MouseClicked(evt);
            }
        });
        combo_subject3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_subject3ActionPerformed(evt);
            }
        });

        jLabel19.setText("Subject 2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 201, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_subject3, 0, 255, Short.MAX_VALUE)
                            .addComponent(combo_subject4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_subject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_subject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txt_year2.setEditable(false);

        jLabel20.setText("Year");

        txt_semester2.setEditable(false);

        jLabel21.setText("Semester");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_year2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_semester2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_semester2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //For the first semester

    void select_compulsory_subjects1() {//compulsory subjects to view in the subject selection form
        String semesterArray[] = db.getStudentCurrentSemester(stu_id);
        String semester = semesterArray[0];
        String yearArray[] = db.getStudentCurrentYear(stu_id);
        String year = yearArray[0];
        String arraySub[] = db.getCompulosorySubjectUg(semester, year, faculty, course_tps);
        select_subject_1.setText(arraySub[0]);
        select_subject_2.setText(arraySub[1]);
        select_subject_3.setText(arraySub[2]);
        select_subject_4.setText(arraySub[3]);
    }

    void select_optional_subjects1() {
        try {

            String semesterArray[] = db.getStudentCurrentSemester(stu_id);
            String semester = semesterArray[0];
            String yearArray[] = db.getStudentCurrentYear(stu_id);
            String year = yearArray[0];
            con = (Connection) DriverManager.getConnection(url, username, password);
            String query = "SELECT subject_name from subject_ug WHERE semester=? AND year =? AND selection=? AND faculty=?";
            pst = (PreparedStatement) con.prepareStatement(query);
            pst.setString(1, semester);
            pst.setString(2, year);
            pst.setString(3, "optional");
            pst.setString(4, faculty);
            res = pst.executeQuery();
            int i = 0;
            while (res.next()) {
                combo_subject1.addItem(res.getString(1));
                combo_subject2.addItem(res.getString(1));
                i++;
            }

        } catch (Exception e) {
            System.out.println(e);

        }
    }

    void setSemester1() {
        String semesterArray[] = db.getStudentCurrentSemester(stu_id);
        String semester = semesterArray[0];
        txt_semester1.setText(semester);
    }

    void setYear1() {
        String yearArray[];
        yearArray = db.getStudentCurrentYear(stu_id);
        String year = yearArray[0];
        txt_year1.setText(year);
    }

    void select_compulsory_subjects2() {//compulsory subjects to view in the subject selection form
        int sem;
        String yearArray[] = db.getStudentCurrentYear(stu_id);
        String year = yearArray[0];
        String semesterAr[] = db.getStudentCurrentSemester(stu_id);
        sem = Integer.parseInt(semesterAr[0]);
        sem += 1;
        String seme = Integer.toString(sem);//seme means the semester variable for the next semester
        String arraySub[] = db.getCompulosorySubjectUg(seme, year, faculty, course_tps);
        select_subject_5.setText(arraySub[0]);
        select_subject_6.setText(arraySub[1]);
        select_subject_7.setText(arraySub[2]);
        select_subject_8.setText(arraySub[3]);
    }

    //For the second semester
    void select_optional_subjects2() {
        try {
            String yearArray[] = db.getStudentCurrentYear(stu_id);
            String year = yearArray[0];
            int sem;
            String semesterAr[] = db.getStudentCurrentSemester(stu_id);
            sem = Integer.parseInt(semesterAr[0]);
            sem += 1;
            String seme = Integer.toString(sem);//seme means the semester variable for the next semester
            con = (Connection) DriverManager.getConnection(url, username, password);
            String query = "SELECT subject_name from subject_ug WHERE semester=? AND year =? AND selection=? AND faculty=?";
            pst = (PreparedStatement) con.prepareStatement(query);
            pst.setString(1, seme);
            pst.setString(2, year);
            pst.setString(3, "optional");
            pst.setString(4, faculty);
            res = pst.executeQuery();
            int i = 0;
            while (res.next()) {
                combo_subject3.addItem(res.getString(1));
                combo_subject4.addItem(res.getString(1));
                i++;
            }

        } catch (Exception e) {
            System.out.println(e);

        }
    }

    void setSemester2() {
        int sem;
        String semesterAr[] = db.getStudentCurrentSemester(stu_id);
        sem = Integer.parseInt(semesterAr[0]);
        sem += 1;
        txt_semester2.setText(Integer.toString(sem));
    }

    void setYear2() {
        String yearArray[] = db.getStudentCurrentYear(stu_id);
        String year = yearArray[0];
        txt_year2.setText(year);
    }

    private void select_subject_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_subject_1ActionPerformed

    }//GEN-LAST:event_select_subject_1ActionPerformed

    private void select_subject_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_subject_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_subject_2ActionPerformed

    private void select_subject_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_subject_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_subject_3ActionPerformed

    private void select_subject_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_subject_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_subject_4ActionPerformed

    private void combo_subject1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_subject1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_subject1MouseClicked

    private void combo_subject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_subject1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_subject1ActionPerformed

    private void select_subject_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_subject_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_subject_5ActionPerformed

    private void select_subject_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_subject_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_subject_6ActionPerformed

    private void select_subject_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_subject_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_subject_7ActionPerformed

    private void select_subject_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_subject_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_subject_8ActionPerformed

    private void combo_subject3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_subject3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_subject3MouseClicked

    private void combo_subject3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_subject3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_subject3ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String semesterArray[] = db.getStudentCurrentSemester(stu_id);
        String semester = semesterArray[0];
        String yearArray[] = db.getStudentCurrentYear(stu_id);
        String year = yearArray[0];
        String arraySub1[] = db.getCompulosorySubjectUg(semester, year, faculty, course_tps);//get compulsory subjects for the semester in section 1 to insert to the database

        StudentSubjects stu = new StudentSubjects(); //create a student subject object to insert subjects of the student to the database
        stu.setStu_id(stu_id);
        stu.setFaculty(faculty);
        stu.setSemester(semester);
        stu.setYear(year);
        stu.setCom_sub1(arraySub1[0]);
        stu.setCom_sub2(arraySub1[1]);
        stu.setCom_sub3(arraySub1[2]);
        stu.setCom_sub4(arraySub1[3]);
        stu.setOpt_sub1(combo_subject1.getSelectedItem().toString());
        stu.setOpt_sub2(combo_subject2.getSelectedItem().toString());
        stu.setCourse_type(course_tps);
        int x = db.setStudentUgSubjects(stu);

        StudentExamResult ser = new StudentExamResult(); // object related to student exam results
        // add zero marks to the student marks for each subject when enrolling to the courses
        String semesterArrayx[] = db.getStudentCurrentSemester(stu_id);
        String semesterx = semesterArrayx[0];
        ser.setFaculty(faculty);
        ser.setYear(year);
        ser.setSemester(semesterx);
        ser.setStu_id(stu_id);
        int ck = 0;// to check whether optional subjects are identical
        // for semester 1 exam result 0 compulsory subjects 
        for (int r = 0; r < 4; r++) {
            ser.setSubject(arraySub1[r]);
            int zr = dbm.setStudentUgresult0(ser);
            ck += zr;
        }
        // for optional subjcets
        ser.setSubject(stu.getOpt_sub1());
        int z1 = dbm.setStudentUgresult0(ser);
        ser.setSubject(stu.getOpt_sub2());
        int z2 = dbm.setStudentUgresult0(ser);

        ck += (z1 + z2);

        int seme;
        seme = Integer.parseInt(semester);
        seme += 1;

        String arraySub2[] = db.getCompulosorySubjectUg(Integer.toString(seme), year, faculty, course_tps);//get compulsory subjects for the semester in section 2 to insert to the database

        ser.setSemester(Integer.toString(seme));
        // for semester 2 exam result 0 compulsory subjeccts
        for (int r = 0; r < 4; r++) {
            ser.setSubject(arraySub2[r]);
            int zr = dbm.setStudentUgresult0(ser);
            ck += zr;
        }

        stu.setStu_id(stu_id);
        stu.setFaculty(faculty);
        stu.setSemester(Integer.toString(seme));
        stu.setYear(year);
        stu.setCom_sub1(arraySub2[0]);
        stu.setCom_sub2(arraySub2[1]);
        stu.setCom_sub3(arraySub2[2]);
        stu.setCom_sub4(arraySub2[3]);
        stu.setOpt_sub1(combo_subject3.getSelectedItem().toString());
        stu.setOpt_sub2(combo_subject4.getSelectedItem().toString());

        //for optional subjects semester 2 exam result 0
        ser.setSubject(stu.getOpt_sub1());
        int z3 = dbm.setStudentUgresult0(ser);
        ser.setSubject(stu.getOpt_sub2());
        int z4 = dbm.setStudentUgresult0(ser);
        ck += (z3 + z4);
        int y = db.setStudentUgSubjects(stu);
        System.out.println(ck);
        if (x == 1 && y == 1 && ck == 12) {
            JOptionPane.showMessageDialog(this, "Student added Successfully..");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error! Try Again..");
        }
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectSubjectFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectSubjectFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectSubjectFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectSubjectFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectSubjectFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JComboBox<String> combo_subject1;
    private javax.swing.JComboBox<String> combo_subject2;
    private javax.swing.JComboBox<String> combo_subject3;
    private javax.swing.JComboBox<String> combo_subject4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField select_subject_1;
    private javax.swing.JTextField select_subject_2;
    private javax.swing.JTextField select_subject_3;
    private javax.swing.JTextField select_subject_4;
    private javax.swing.JTextField select_subject_5;
    private javax.swing.JTextField select_subject_6;
    private javax.swing.JTextField select_subject_7;
    private javax.swing.JTextField select_subject_8;
    private javax.swing.JTextField txt_semester1;
    private javax.swing.JTextField txt_semester2;
    private javax.swing.JTextField txt_year1;
    private javax.swing.JTextField txt_year2;
    // End of variables declaration//GEN-END:variables
}
